[package]
name = "warduino"
version = "0.1.0"
authors = ["Tom Lauwaerts <tom.lauwaerts@ugent.be>"]
description = "Library for WARDuino primitives"
edition = "2018"
include = [
    "Cargo.toml",
    "LICENSE",
    "/README.md",
    "/src/**",
    "examples"
]
keywords = ["warduino", "wasm"]
license = "MPL-2.0"

[dependencies]
num = { version = "0.4.3", default-features = false }
num-derive = { version = "0.4.2", default-features = false }
num-traits = { version = "0.2.19", default-features = false }


[[example]]
name = "blink"
crate-type = ["cdylib"]

[[example]]
name = "button"
crate-type = ["cdylib"]

[[example]]
name = "hello"
crate-type = ["cdylib"]

[[example]]
name = "smartlamp"
crate-type = ["cdylib"]
